#!/bin/sh

SERVICE="disable"
if [ -f /boot/config/domain.cfg ]; then
	source /boot/config/domain.cfg
fi

if [ "$SERVICE" = "enable" ]; then
	# mount xml/conf image if not already mounted
	if [ ! "$(mount | grep domain.img)" ]; then
	  mount -t ext4 /boot/config/plugins/dynamix.kvm.manager/domain.img /etc/libvirt
	  mkdir -p /etc/libvirt/hooks
	  cp /boot/config/plugins/dynamix.kvm.manager/qemu /etc/libvirt/hooks/
	fi

	# Start libvirt
	if [ -x /etc/rc.d/rc.libvirt ]; then
	  logger "Starting libvirt"
	  /etc/rc.d/rc.libvirt start |& logger
	fi
fi
