#!/bin/sh

# Only start if array has started in Normal operation mode
if grep -q 'fsState="Started"' /var/local/emhttp/var.ini && grep -q 'startMode="Normal"' /var/local/emhttp/var.ini; then
	# Start Docker.io
	if [ -x /etc/rc.d/rc.docker ]; then
		echo "Starting Docker..."
		/etc/rc.d/rc.docker start | logger
		/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/dockerupdate.php | logger
	fi
fi
