#!/bin/bash
# usage: background start logfile cmd
# usage: background cancel cmd
# usage: background status cmd
#set -x
oper=$1
shift 1
case "$oper" in
'start')
  log=$1
  shift 1
  args="$@"
  if ! pgrep -f "^$args" ; then
    $@ &>$log &
  fi
  exit
;;
'cancel')
  args="$@"
  pkill -f "^$args"
  exit
;;
'status')
  args="$@"
  pgrep -f "^$args"
  exit
;;
esac
