#!/usr/bin/php
<?PHP
/* Copyright 2015, Bergware International.
 * Copyright 2015, Lime Technology
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
if ($argv[1]) {
  $zip = $argv[1];
} else {
  exec("mkdir -p /boot/logs");
  $var = parse_ini_file("/var/local/emhttp/var.ini");
  $zip = "/boot/logs/".str_replace(' ','_',strtolower($var['NAME']))."-diagnostics-".date('Ymd-Hi').".zip";
}
$diag = basename($zip, '.zip');
exec("mkdir -p /$diag/array /$diag/system /$diag/config /$diag/syslog /$diag/shares /$diag/smart");
file_put_contents("/$diag/array/array.txt", str_replace("\n","\r\n",print_r(parse_ini_file('/var/local/emhttp/disks.ini',true),true)));
exec("lsscsi|todos >/$diag/system/lsscsi.txt");
exec("lspci|todos >/$diag/system/lspci.txt");
exec("free -mt|todos >/$diag/system/memory.txt");
exec("ifconfig -s|grep -Po '^(eth|bond)[0-9]+'", $ports);
foreach ($ports as $port) {
  exec("ethtool $port|todos >>/$diag/system/ethtool.txt");
  file_put_contents("/$diag/system/ethtool.txt", "\r\n", FILE_APPEND);
  exec("ethtool -i $port|todos >>/$diag/system/ethtool.txt");
  file_put_contents("/$diag/system/ethtool.txt", "--------------------------------\r\n", FILE_APPEND);
}
exec("ifconfig|todos >/$diag/system/ifconfig.txt");
exec("cp /boot/config/*.{cfg,conf,dat} /boot/config/go /$diag/config");
if (is_dir("/boot/config/shares")) exec("cp /boot/config/shares/*.cfg /$diag/shares");
$ini = "/var/local/emhttp/shares.ini";
$shares = file_exists($ini) ? parse_ini_file($ini, true) : array();
foreach ($shares as $share) {
  $file = "/$diag/shares/${share['name']}.cfg";
  if (!file_exists($file)) file_put_contents($file,"# This share has default settings.\n");
}
foreach (glob("/var/log/syslog*") as $file) {
  exec("todos <$file >/$diag/syslog/".basename($file).".txt");
}
exec("ls -l /dev/disk/by-id/[au]*|awk '$0!~/-part/{split($11,a,\"/\");print a[3],substr($9,21)}'", $devices);
foreach ($devices as $device) {
  $disk = explode(' ',$device);
  exec("smartctl -a /dev/${disk[0]}|todos >/$diag/smart/${disk[1]}.txt");
}
exec("zip -qmr $zip /$diag");
?>
