#!/usr/bin/php
<?PHP
/* Copyright 2015, Bergware International.
 * Copyright 2015, Lime Technology
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
if ($argv[1]) {
  $zip = $argv[1];
} else {
  echo "Starting diagnostics collection... ";
  exec("mkdir -p /boot/logs");
  $var = @parse_ini_file("/var/local/emhttp/var.ini");
  $server = isset($var['NAME']) ? str_replace(' ','_',strtolower($var['NAME'])) : 'tower';
  $zip = "/boot/logs/$server-diagnostics-".date('Ymd-Hi').".zip";
}
$diag = basename($zip, '.zip');
exec("mkdir -p /$diag/system /$diag/config /$diag/logs /$diag/shares /$diag/smart /$diag/qemu");
foreach (glob("/var/local/emhttp/*.ini") as $file) file_put_contents("/$diag/system/vars.txt",preg_replace(array("/\n/","/^Array/"),array("\r\n",basename($file,".ini")),print_r(parse_ini_file($file,true),true)),FILE_APPEND);
exec("sed -r -i '/\[(reg|flash).*\]/d' /$diag/system/vars.txt"); // remove registration and flash info
exec("lsscsi -vgl|todos >/$diag/system/lsscsi.txt");
exec("lspci -knn|todos >/$diag/system/lspci.txt");
exec("free -mt|todos >/$diag/system/memory.txt");
exec("ps -ef|todos >/$diag/system/ps.txt");
exec("lsof -Pni|todos >/$diag/system/lsof.txt");
exec("ifconfig -s|grep -Po '^(eth|bond)[0-9]+'", $ports);
foreach ($ports as $port) {
  exec("ethtool $port|todos >>/$diag/system/ethtool.txt");
  file_put_contents("/$diag/system/ethtool.txt", "\r\n", FILE_APPEND);
  exec("ethtool -i $port|todos >>/$diag/system/ethtool.txt");
  file_put_contents("/$diag/system/ethtool.txt", "--------------------------------\r\n", FILE_APPEND);
}
exec("ifconfig|todos >/$diag/system/ifconfig.txt");
exec("find /sys/kernel/iommu_groups/ -type l|todos >/$diag/system/iommu_groups.txt");
exec("todos </proc/cmdline >/$diag/system/cmdline.txt");
exec("cp /boot/config/*.{cfg,conf,dat} /boot/config/go /$diag/config 2>/dev/null");
if (is_dir("/boot/config/shares")) exec("cp /boot/config/shares/*.cfg /$diag/shares 2>/dev/null");
$ini = "/var/local/emhttp/shares.ini";
$shares = file_exists($ini) ? parse_ini_file($ini, true) : array();
foreach ($shares as $share) {
  $file = "/$diag/shares/${share['name']}.cfg";
  if (!file_exists($file)) file_put_contents($file,"# This share has default settings.\r\n");
}
foreach (glob("/var/log/syslog*") as $file) {
  exec("todos <$file >/$diag/logs/".basename($file).".txt");
}
$docker = "/var/log/docker.log";
if (file_exists($docker)) exec("todos <$docker >/$diag/logs/docker.log");
$libvirtd = "/var/log/libvirt/libvirtd.log";
if (file_exists($libvirtd)) exec("todos <$libvirtd >/$diag/logs/libvirtd.log");
$qemu = glob("/var/log/libvirt/qemu/*.log*");
if ($qemu)
  foreach ($qemu as $file) exec("todos <".escapeshellarg($file)." >/$diag/qemu/".escapeshellarg(basename($file)));
else
  file_put_contents("/$diag/qemu/no qemu log files","");
exec("ls -l /dev/disk/by-id/[au]* 2>/dev/null|awk '$0!~/-part/{split($11,a,\"/\");print a[3],substr($9,21)}'", $devices);
exec("grep -Po '(\/dev\/\K[sh]d[a-z]+|\/\K(usb|ata)\d+)' /$diag/system/lsscsi.txt 2>/dev/null", $ata);
foreach ($devices as $device) {
  $disk = explode(' ',$device);
  $port = "unkown";
  for ($i=0; $i<count($ata); $i++) if ($disk[0]==$ata[$i]) {$port = $ata[$i+1]; break;}
  exec("smartctl -a /dev/${disk[0]}|todos >/$diag/smart/${disk[1]}_$port.txt");
}
exec("zip -qmr $zip /$diag");
if (!$argv[1]) echo "done.\nZIP file '$zip' created.\n";
?>
