#!/usr/bin/php -q
<?PHP
/* Copyright 2015, Bergware International.
 * Copyright 2015, Lime Technology
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
echo "<p style='text-align:center'><span class='error label'>Error</span><span class='warn label'>Warning</span><span class='system label'>System</span><span class='array label'>Array</span></p>\n";

require_once '/usr/local/emhttp/webGui/include/ColorCoding.php';

$ata = exec("ls -n /sys/block/{$argv[1]}|grep -Po 'ata\d+'");
$dev = $ata ? "${argv[1]}|${ata}[.:]" : $argv[1];

exec("grep -P '$dev' /var/log/syslog", $lines);

foreach ($lines as $line) {
  if (strpos($line,'disk_log')!==false) continue;
  $span = "span";
  foreach ($match as $type) foreach ($type['text'] as $text) if (preg_match("/$text/i",$line)) {$span = "span class='{$type['class']}'"; break 2;}
  echo "<$span>".htmlentities($line)."</span>\n";
}
?>