#!/bin/bash
app=$(basename $0)
dev=$1
ata=$(ls -l /sys/dev/block|grep -m1 "$dev$"|grep -Po 'ata[\d]+')
if [[ -n $ata ]]; then
  exec grep -P "($dev|$ata(?!\d))" /var/log/syslog | grep -v $app
else
  exec grep "$dev" /var/log/syslog | grep -v $app
fi
