#!/usr/bin/php
<?PHP
/* Copyright 2015, Bergware International.
 * Copyright 2015, Lime Technology
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
require_once "/usr/local/emhttp/webGui/include/Wrappers.php";

$plugin = "/usr/local/sbin/plugin";
$notify = "/usr/local/sbin/notify";

exec("wget -qO /dev/null 127.0.0.1$(lsof -lbnPi4 -sTCP:LISTEN|awk '$1==\"emhttp\"{print substr($9,index($9,\":\"))}')/update.htm?cmdStatus=apply");

$var    = parse_ini_file("/var/local/emhttp/var.ini");
$unraid = parse_plugin_cfg("dynamix",true);
$server = strtoupper($var['NAME']);
$output = $unraid['notify']['plugin'];

exec("$plugin checkall >/dev/null");
foreach (glob("/tmp/plugins/*.plg", GLOB_NOSORT) as $file) {
  $plg = basename($file);
  $old = exec("$plugin version '/var/log/plugins/$plg'");
  $new = exec("$plugin version '$file'");
  if ($new && strcmp($new, $old) > 0) {
    $name = basename($file, '.plg');
    exec("$notify -e 'Plugin: $name' -s 'Notice [$server] - New version available' -d 'Version $old updated to version $new' -i 'normal $output' -x");
  }
  unlink($file);
}

exit(0);
?>
