#!/bin/bash
# reiserfsck start <dev> <id> <options>
# reiserfsck status <dev> <id>
# reiserfsck cancel <dev> 

case "$1" in
'start')
  /sbin/reiserfsck $2 --yes --quiet $4 &> /var/lib/reiserfs/check.status.$3 &
;;
'status')
  if [ -f /var/lib/reiserfs/check.status.$3 ]; then
    cat /var/lib/reiserfs/check.status.$3
  else
    echo "Not available"
  fi;
  pgrep -f "/sbin/reiserfsck $2" >/dev/null
;;
'cancel')
  pkill -f "/sbin/reiserfsck $2"
;;
esac
