#!/bin/sh

# Shutdown xendomains
if [ -d /proc/xen ]; then
  if [ -x /etc/rc.d/rc.xendomains ]; then
    logger "Stopping XEN domains:  /etc/rc.d/rc.xendomains"
    /etc/rc.d/rc.xendomains stop | logger
  fi
  rm -r /etc/xen/auto/* &> /dev/null
fi
